### ISSUE TITLE
Exploratory on OpenSearch Dashboards: Community Member Insights

### ISSUE THREAD

**Issue by apasun** [opensearch-project/project-website#1461]
**Describe the blog post your would like to write**
The OpenSearch Projects team recently conducted an exploratory study with the OpenSearch community members on OpenSearch Dashboards. This blog discusses main findings and pain points that community members surfaced. 

**What is the title of the blog post?**
Exploratory on OpenSearch Dashboards: Community Member Insights

**Who are the authors?**
Aparna Sundar

**What is the proposed posting date?**
March 27th 2023

**Comment by pajuric** [comment]
@apasun - Checking in on this to see what the new publish date is for this content. Will this publish to the OpenSearch blog or is this going on the forum?

**Comment by pajuric** [comment]
# 04 OpenSearch Community - Exploratory on OpenSearch Dashboards: Community Member Insights

***Published Date: TBD***
***Github new issue: https://github.com/opensearch-project/project-website/issues/1461***

***Link: OpenSearch Blog***
* * *

# OpenSearch Dashboards: Community Insights

Wed, May 24, 2023 - Aparna Sundar

In February of 2023, the OpenSearch Projects team talked to seven OpenSearch community members about their experience with using [OpenSearch Dashboards](https://opensearch.org/docs/latest/dashboards/index/). These community members were selected because they responded to a call for participants in one of our [community meetings](https://forum.opensearch.org/t/opensearch-community-meeting-2023-0131/11892). We wanted to recruit OpenSearch community members who regularly created dashboards, so we could explore their pain points and frustrations. Dashboards are typically created by community members who either consume the dashboards themselves, or they create dashboards that are consumed by their community members (that is, dashboard consumers). 

The study participants contextualized OpenSearch as a developer tool, and highlighted the need to simplify things for community members who attempted to “just create dashboards.” The participants noted that they struggled with the usability of dashboards, found the dashboard offerings limited, and shared frustrations with learnability, discoverability, and the complexity of integrating with their platform’s UI. They shared other frustrations with regards to documentation, dashboard creation, sharing, anomaly detection, and usage of space on the OpenSearch dashboards. 

While some participants called out the importance of setting up the index templates correctly for an improved downstream experience, others highlighted frustrations with this step in dashboard creation as being distinct from the experience of creating dashboards on other tools. Participants also called out the benefits of creating standards in the encoding and permissions process. 

Participants called out many inconsistencies and deficiencies in the visualization functionality in OpenSearch. This included color coding, interchangeability of charts, filter application, and zooming in and out of a chart. Given the range of dashboard creator needs, participants expect OpenSearch to streamline dashboard creation, and in addition, provide enhanced functionality in order to maximize usage of OpenSearch dashboards. Ultimately, participants want to have a quick and easy way to set up the basic essentials for dashboarding, and then make sure the dashboarding process is part of the automation (that is, CICD pipeline). 

When asked what their ideal dashboard experience would be, we obtained a variety of responses that indicated deficiencies in the current OpenSearch dashboard experience. Participants wanted basic abilities stemming from a need for increased usability, simplicity, and a confidence in knowing that what they were seeing in dashboards helped them solve their immediate business problem. Some other participants were more aspirational in sharing what they would want in an ideal dashboard experience, and described a need for automated visualizations based on common data structures that can be identified in the user’s data. 

We are currently reviewing and consolidating all feedback. Further studies are taking place over the course of the next few months, and we encourage you to participate. Our roadmap is completely driven by community members, like you. If you are interested, please join our _bi-weekly community meetings_ to hear about opportunities for future studies, or [sign up here](https://www.meetup.com/opensearch/). Thanks so much for reading and we look forward to continued input from the OpenSearch community.

**Comment by pajuric** [comment]
@nateynateynate and @krisfreedain - Created this as a markdown file per Daryll's suggestion.

**Comment by pajuric** [comment]
@nateynateynate - I'd like to test distributing this blog using the new process we discussed with Daryll. Can we try pushing this later this week?

**Comment by hdhalter** [comment]
It still needs to go through editorial, so once you get it into a PR, Nathan will review and I'll make the changes. Can you please link the PR to this issue when ready?

**Comment by nateynateynate** [comment]
@natebower - if you have no strong objection, we've decided to try something a bit faster and wysiwyg oriented while we're in the face of low staffing resources and seriously full daily schedules. 

If you could select the sentences you want changed with your mouse and then hit the 'quote reply' button, you can type your suggested edits here in the issue's discussion. This way we still retain an audit trail.

![image](https://github.com/opensearch-project/project-website/assets/96254688/d77b5755-c9bd-48f7-8242-f482461caac5)

It should add a comment input section with your selected section in a quote block where you can type your suggested edits.

We'd really like to start separating the editorial process from the publish process. There's no need to wait for a PR.

Humor us for a few rounds of this to see how much faster we can publish content?

**Comment by nateynateynate** [comment]
> # 04 OpenSearch Community - Exploratory on OpenSearch Dashboards: Community Member Insights
> 
> _**Published Date: TBD**_ _**Github new issue: #1461**_
> 
> _**Link: OpenSearch Blog**_
> # OpenSearch Dashboards: Community Insights
> 
> Wed, May 24, 2023 - Aparna Sundar
> 
> In February of 2023, the OpenSearch Projects team talked to seven OpenSearch community 

OpenSearch Project community? 

>members about their experience with using [OpenSearch Dashboards](https://opensearch.org/docs/latest/dashboards/index/). These community members were selected because they responded to a call for participants in one of our [community meetings](https://forum.opensearch.org/t/opensearch-community-meeting-2023-0131/11892). We wanted to recruit OpenSearch community members who regularly created dashboards, so we could explore their pain points and frustrations. Dashboards are typically created by community members who either consume the dashboards themselves, or they create dashboards that are consumed by their community members (that is, dashboard consumers).

**Comment by nateynateynate** [comment]
Or even copy paste the whole thing with your edits with the note that its okay to publish.

**Comment by natebower** [comment]
Unfortunately that takes away my ability to directly edit the text and to verify that my changes were made. Additionally, we need these to be in a PR in order to use the new automated style workflow. @kolchfa-aws Can you put this into a PR due to low bandwidth on the Marketing side? If so, I can edit and approve tomorrow. Thanks!

**Comment by nateynateynate** [comment]
> Unfortunately that takes away my ability to directly edit the text and to verify that my changes were made. 

   You can check when we file a PR. Drafting shouldn't be done through a PR, but with a finished product not expecting to need any further edits. 

>Additionally, we need these to be in a PR in order to use the new automated style workflow. @kolchfa-aws Can you put this into a PR due to low bandwidth on the Marketing side? If so, I can edit and approve tomorrow. Thanks!

I'm not sure what you mean by the new automated style workflow? We've got the vale hinters and all of the same style hinting in our website-repo that you do. There's really no need to file a PR until most of the drafting and edits are done.

**Comment by pajuric** [comment]
@natebower @nateynateynate @kolchfa-aws @apasun - Let's at least test this new issue process. I is a small ask for a possible process improvement. If it doesn't work or fit our needs, then we go back to editing in the PR. But we need to know or see if this is a plausible solution since the editing in a PR process is a major inhibitor for blog contributors.

**Comment by hdhalter** [comment]
Sounds good, @pajuric. I can record the post-editorial process or we can huddle if you want to see it live.

**Comment by nateynateynate** [comment]
@natebower - looks like there was some work on a quip document. Is everything decent enough to file a PR for with the markdown? I think we're ready if you are.

**Comment by hdhalter** [comment]
@nateynateynate - I'll get this into markdown so you can create the PR.

**Comment by hdhalter** [comment]
# OpenSearch Dashboards: Community Insights

In February of 2023, the OpenSearch Project conducted user interviews with seven OpenSearch community members about their experience using OpenSearch Dashboards. These community members were selected because they responded to a call for participants in one of our [community meetings](https://forum.opensearch.org/t/opensearch-community-meeting-2023-0131/11892). We wanted to recruit OpenSearch community members who regularly created dashboards so that we could explore user pain points and frustrations. Dashboards are typically created by OpenSearch users who either consume the dashboards themselves or who create dashboards that are consumed by other users (that is, dashboard consumers). 

The study participants contextualized OpenSearch as a developer tool and highlighted the need to simplify things for OpenSearch users who attempt to “just create dashboards.” The participants noted that they struggled with the usability of dashboards, found the dashboard offerings limited, and shared frustrations with learnability, discoverability, and the complexity of integrating with their platform’s UI. They shared other frustrations regarding documentation, dashboard creation, sharing, anomaly detection, and usage of space on dashboards. 

While some participants called out the importance of setting up the index templates correctly for an improved downstream experience, others highlighted frustrations with this step in dashboard creation as being distinct from the experience of creating dashboards with other tools. Participants also noted the benefits of creating standards in the encoding and permissions processes. 

Participants in this study called out many inconsistencies and deficiencies in the visualization functionality in OpenSearch. This included color coding, interchangeability of charts, filter application, and zooming in and out of a chart. Given the range of dashboard creator needs, participants expect OpenSearch to streamline dashboard creation and, in addition, provide enhanced functionality in order to maximize usage of OpenSearch Dashboards. Ultimately, participants want to have a quick and easy way to set up the basic essentials in a dashboard and then make sure the dashboarding process is part of the automation (that is, a continuous integration and delivery [CI/CD] pipeline). 

When asked what their ideal dashboard experience would be, we obtained a variety of responses that indicated deficiencies in the current OpenSearch Dashboards experience. Participants wanted basic abilities stemming from a need for increased usability, simplicity, and a confidence in knowing that what they were seeing in dashboards helped them solve their immediate business problem. Some other participants were more aspirational in sharing what they would want in an ideal dashboard experience and described a need for automated visualizations based on common data structures that can be identified in the user’s data. 

We are currently reviewing and consolidating all feedback. Further studies are taking place over the course of the next few months, and we encourage you to participate. Our roadmap is completely driven by community members, like you. If you are interested, please join our _bi-weekly community meetings_ to hear about opportunities for future studies, or sign up _here_. Thanks so much for reading, and we look forward to continued input from the OpenSearch community!

**Comment by pajuric** [comment]
Wreiting the meta for this now.

**Comment by natebower** [comment]
> @natebower - looks like there was some work on a quip document. Is everything decent enough to file a PR for with the markdown? I think we're ready if you are.

@nateynateynate Yes, this is already edited and approved for publishing.

**Comment by nateynateynate** [comment]
> @nateynateynate Yes, this is already edited and approved for publishing.

Awesome. Thanks.

**Comment by pajuric** [comment]
I think we need to check that all he links picked up in the Quip markdown file. Looks like a 1-2 might be missing?

**Comment by pajuric** [comment]
**Meta for this post:** 

**meta_keywords:**  OpenSearch dashboards, OpenSearch user experience, OpenSearch exploratory study, OpenSearch users
**meta_description:**  Learn how OpenSearch Project conducts user interviews to help improve OpenSearch Dashboards and how you can participate in future studies.
