### ISSUE TITLE
Titaniam Exhibitor Profile

### ISSUE THREAD

**Issue by kevinbarcellos** [opensearch-project/project-website#1918]
**NOTE: This is an issue template for new partner pages we are building. Existing partners can use them to submit information needed as we build out enhanced pages. New partners, please continue to use the process outlined here for the time being: https://opensearch.org/new-partner.html

**Organization name**
Please let us know the exact business name

**Brief description of your business and what it does (50 words or less)**
A clear and concise description of your business.

**Name of your relevant product(s) or service for the OpenSearch audience**
A clear and concise description of your product(s) and/or services offered to the OpenSearch community.

**What OpenSearch technologies do you specialize in**
Is there an area of the project where your business specializes?
(e.g., search, analytics, observability, security, or other)

**Type of business**
(e.g., MSP, CSP, ISV, product/technology, services organization, other). If other, please define.
This will inform the community how they can expect to use your product(s) and services.

**Home/main office location or address**
Home/main office location or address (if applicable)

**How can people contact you (email and phone)**
email / phone (if applicable)

**Regions you serve**
(e.g.,North America, South America, Europe, Middle East, Africa, Asia Pacific, Australia)
What regions of the world do you serve?

**Industry specialization**
(e.g. business services, consumer services, education, energy and utilities, financial services, healthcare, media and entertainment, public sector, non-profit, retail, software and technology)? Add all that apply.

**Logo**
Please upload a company logo
![Titaniam Logo](https://github.com/opensearch-project/project-website/assets/141960684/4bb2bce9-4209-4fa6-bb16-8d2ba5ce8ccd)**Additional image**
Attach any additional image you would like to provide that showcase your business (product, technology, offices)
![Snip20230823_8](https://github.com/opensearch-project/project-website/assets/141960684/185b3237-ac94-4cf3-b32c-223a34a91350)

**Links**
Add links to your last three blogs that are relevant for the OpenSearch Project audience.

https://titaniam.io/opensearch-partner-highlight-how-titaniam-arcus-can-further-secure-your-opensearch-deployment/

https://titaniam.io/opensearch-partner-highlight-byok-for-b2b-saas-operators-using-opensearch/

https://titaniam.io/securing-data-in-elasticsearch-and-opensearch/

**Comment by pajuric** [comment]
@kevinbarcellos - Thank you for submitting your page info. 

@astephanus - ping!

**Comment by pajuric** [comment]
@kevinbarcellos - I wrote up a company profile for Titaniam since we need content for all the fields in order to build your partner page. If you could review the content provide below and provide feedback, edits, and/or approval to publish, I would appreciate it. 



#### Organization name:

**Titaniam, Inc.** 


#### Brief description of your business and what it does (50 words or less)

Titaniam is the market leader in high-performance encryption-in-use that keeps valuable data secure even if the enterprise is breached and its data stolen. With the ability to process data without decryption and release it in nine different private formats, Titaniam is the answer that the market needs to address ransomware and extortion, insider threats, and data privacy enforcement. 


#### Name of your relevant product(s) or service for the OpenSearch audience


The Titaniam data security platform converges 10 security and privacy controls into a single enterprise-grade solution, that delivers unprecedented security at a fraction of the price. With six modules covering the breath of enterprise architectures and out-of-the-box support for a full range of data security and privacy controls, Titaniam is the most powerful and versatile data security platform in the market today. Titaniam offers advanced data security controls like encryption-in-use, searchable encryption, and analyzable data tokenization. This includes a full breadth of controls, such as traditional and format preserving encryption, vaulted and vaultless data tokenization, static and dynamic masking, anonymization and a full range of key based controls such as BYOK and HYOK in a single solution. 

[Titaniam’s AWS OpenSearch Security Plugin](https://titaniam.io/solutions/aws-opensearch-security/) enables sensitive data to be indexed and searched while still retaining FIPS 140-2 certified encryption at all times, keeping your valuable data safe and ransomware and extortion proof. 


**What OpenSearch technologies do you specialize in?**
Security, TLD certificates, Authentication backends, Role-cased access control, OpenSearch Dashboards multi-tenancy, Audit logging.  



#### **Type of business**

Product/technology, Professional Services Organization


#### Home/main office location or address


San Jose, CA; Chennai, India


#### How can people contact you (email and phone):

[+1 (408) 533-0782](tel:+14085330782)
[info@titaniam.io](mailto:info@titaniam.io)

#### Regions you serve

Worldwide

#### **Industry specialization**

All


#### Add links to your last three blogs that are relevant for the OpenSearch Project audience

https://titaniam.io/opensearch-partner-highlight-how-titaniam-arcus-can-further-secure-your-opensearch-deployment/
https://titaniam.io/opensearch-partner-highlight-byok-for-b2b-saas-operators-using-opensearch/
https://titaniam.io/securing-data-in-elasticsearch-and-opensearch/

**Comment by kevinbarcellos** [comment]
Hi Patti,

We had entries for all of these fields in our github submission. Did they
not come through?

I've attached the document here.

Regards,

Kevin

**Comment by pajuric** [comment]
@kevinbarcellos - No, we're not seeing an attachment or reply to the questions on our end. If you have a moment, please email them and I'll make sure they get added to this file.

**Comment by kevinbarcellos** [comment]
Patti -


Please let me know you got this ok.


Regards,


Kevin



**Organization name**

Titaniam, Inc.

**Brief description of your business and what it does (50 words or less)**

Titaniam provides an encryption plugin that provides field level and index
level encryption with externally controlled keys. This enables opensearch
users to consolidate nodes and drive significant cost savings while
retaining data segmentation.  Titaniam is FIPS 140-2 certified encryption
and meets PCI, HIPAA, GDPR and other compliance requirements.


**Name of your relevant product(s) or service for the OpenSearch audience**

Titaniam Plugin for OpenSearch

**What OpenSearch technologies do you specialize in**

Data Segmentation, data security, data privacy, compliance and cost
optimization

**Type of business**

ISV

**Home/main office location or address**

1559 Union Avenue, Suite 3054, Los Gatos CA 95032

**How can people contact you (email and phone)**

***@***.***

408-828-9159

**Regions you serve**

Global

**Industry specialization**

All

**Logo**


**Additional image**




**Links**

Add links to your last three blogs that are relevant for the OpenSearch
Project audience.


https://titaniam.io/opensearch-partner-highlight-how-titaniam-arcus-can-further-secure-your-opensearch-deployment/

https://titaniam.io/opensearch-partner-highlight-byok-for-b2b-saas-operators-using-opensearch/

https://titaniam.io/securing-data-in-elasticsearch-and-opensearch/

**Comment by krisfreedain** [comment]
Done! Thanks all
