### ISSUE TITLE
Fixes needed in the latency comparison section of the concurrent segment search blog post

### ISSUE THREAD

**Issue by ketanv3** [opensearch-project/project-website#2374]
There are some factual errors in the performance results' section of the [concurrent segment search blog post](https://opensearch.org/blog/concurrent_segment_search/):
* The "% improvement" column in the latency comparison table has stats about the "% reduction" instead. We should either rename the column or fix the stats.
  For example, the distance_amount_agg operation went from 15348 ms to 4022 ms which equates to 74% reduction or 3.82x faster or 282% improvement.
* Some rows have rounding off errors.
  For example, the default operation went from 4.25 ms to 4.7 ms which equates to –11% reduction, not –10%.
* Nitpick: Move the unit (ms) from the table header to the relevant columns instead. Otherwise it reads as if all columns have the same unit, which isn't true.

@sohami @reta Folks, can you take a look and fix?

**Comment by sohami** [comment]
> The "% improvement" column in the latency comparison table has stats about the "% reduction" instead. We should either rename the column or fix the stats.
For example, the distance_amount_agg operation went from 15348 ms to 4022 ms which equates to 74% reduction or 3.82x faster or 282% improvement.

My thought was %improvement in latency is implicitly % reduction as latency improvement will come when the new value is low. Hence I mentioned improvement instead of increase/decrease. I don't see a big issue with this (we are even mentioning that +ve is better). But if folks feel we need to call it %reduction explicitly then we can change that. @reta any thoughts ? I don't want to change it to %-faster or x-times faster for now to keep changes minimum. Over next blog we can decide if we want to follow a standard pattern for publishing the numbers and then follow that.

> Some rows have rounding off errors.
For example, the default operation went from 4.25 ms to 4.7 ms which equates to –11% reduction, not –10%.

I was mostly taking the floor of the percentage values, but yes for default case it can be changed. Will fix this.

> Nitpick: Move the unit (ms) from the table header to the relevant columns instead. Otherwise it reads as if all columns have the same unit, which isn't true.

Sure

**Comment by reta** [comment]
> But if folks feel we need to call it %reduction explicitly then we can change that. @reta any thoughts ?

To be fair, % improvement sound quite uncontroversial to me: it reads as it should (the contrary of it would be regression), this is a terminology used fe by Rust team [1] (and I am sure many others), unless I am missing the context of measurement here.

[1] https://github.com/rust-lang/rustc-perf/blob/420012f0bb12281b5a3e897280d3f38b241a4735/triage/2023-10-18.md

**Comment by sohami** [comment]
Thanks @reta. I am also inclining to keep the %improvement in the header as is. Will make the change for fixing the floor %age values and moving ms in the column.

**Comment by ketanv3** [comment]
Thanks for the fixes, @sohami!

> Over next blog we can decide if we want to follow a standard pattern for publishing the numbers and then follow that.

Big +1 on this. I feel that "improvement" is an overloaded term; it could mean lower latency, better (single-threaded) performance, better (multi-core) throughput, lower resource usage, etc.

For example, a reader might think of +73% improvement in distance_amount_agg to also improve the throughput of the system by that amount, which isn't true for concurrent segment search. So I think it helps to be explicit and provide results on the same scale.
