### ISSUE TITLE
OpenSearchCon North America 2024 Registration and CFP are Open

### ISSUE THREAD

**Issue by pajuric** [opensearch-project/project-website#2896]
**Describe the blog post your would like to write**
Provides an update to the community re OpenSearchCon North America 2024, including its location, registration info, and how to submit your CfP. 

**What is the title of the blog post?**
OpenSearchCon North America 2024 Registration and CFP are Open

**Who are the authors?**
Daryll Swager

**What is the proposed posting date?**
5/23

**Comment by dimwetoth** [comment]
MD of the draft blog post below:

Please note that I want TWO stylized CTA buttons that link to the URLs right at the top.  I'd like them to be in-line horizontally if it's possible to do so. I could not figure out how to accomplish that in Markdown, sorry. I'd like the editorial process to happen in here please.

### OpenSearchCon North America 2024 Registration and CFP are Open

CTA BUTTON (open in same window): [REGISTER NOW](https://opensearch.org/events/opensearchcon/2024/north-america/register.html)
CTA BUTTON: (open in same window): [SUBMIT CFP](https://opensearch.org/events/opensearchcon/2024/north-america/cfp.html)

[OpenSearchCon](https://opensearch.org/events/opensearchcon/2024/north-america/index.html) North America is back and coming to the Bay Area! Join us at the Hilton Union Square in San Francisco from September 24-26. The event is in-person only and there is no fee to attend. 

We’re anticipating hundreds of people and dozens of OpenSearch partners this year, which will make for a fun and exciting show. [Special room rates](https://book.passkey.com/e/50823627)are available for those who wish to stay at the event hotel. OpenSearchCon passes are limited, so [register today](https://opensearchcon2023.splashthat.com/) in order to claim your spot at this year’s conference. 

The [Call for Presentations](https://opensearch.org/events/opensearchcon/2024/north-america/cfp.html) is open until the end of the day on June 14. If you have a story you’d like to share, submit your talk NOW - time is of the essence!

Builders will be presenting dozens of sessions across four conference tracks to help you learn more about building applications at scale as an open-source contributor.  The four conference tracks are:

* Search - for all types of search technology enthusiasts
* Analytics, Security, Observability - for those that like to visualize and make data-driven decisions
* Operating OpenSearch - for talks about performance, scalability, interesting implementations, and the like
* Community - focuses on how communities form and grow in the open-source universe, including OpenSearch


This year, the show will kick off with an opening keynote, and then three session rooms will present across a variety of search and analytics topics for the first two days of the conference.  The Search and Analytics tracks will cover a broad range of technology topics, including Search, Open Telemetry, Lucene, Vector Databases, AI/ML, and more. The Operating and Community tracks will focus on performance, scalability, implementation, adoption and community growth. Given the quality of last year’s talks, we’re expecting a very active CFP and bar-raising sessions this year. All sessions will be recorded and we will post them shortly after the conference concludes. We’ll also have free food, drinks, and some fun activities in the evenings of the 24th and 25th!

Given the popularity of last year’s event, our partner round table will return this year. This forum allows partners to talk about the project with the OpenSearch team and each other. The conversation spans a wide variety of topics both highly technical and more community-oriented, and usually focuses on the things that are going really well in the project, and areas that could use a little help.  This is a great forum to listen to feedback from experienced partners who have a vested interest and  opinions about the OpenSearch Project. 

The Unconference will be back as well! First introduced last year, this session format allows you to propose a short talk. Your peers will then vote on whether they want to hear from you and a handful of short sessions will be delivered. These sessions have proven to be fun as well as thought-provoking, so don’t miss out.

On September 26, we’re going to have smaller format training sessions and workshops with enough room for 100 or so people who want to get a more in-depth look at OpenSearch from some of the experts in the field.  Separate signups will be provided for that once the schedule has been finalized, so remember to visit the conference site often to see the latest news and session information.

First and foremost, we just want everyone to come out, have some fun, and learn a bunch of new stuff along the way. See you in San Francisco!

**Resources:**

[Registration Page](https://opensearch.org/events/opensearchcon/2024/north-america/register.html)
[CFP Submission Page](https://opensearch.org/events/opensearchcon/2024/north-america/cfp.html)
[OpenSearchCon Home Page](https://opensearch.org/events/opensearchcon/2024/north-america/index.html)

**Comment by pajuric** [comment]
@nateynateynate @krisfreedain  - Can we push this one out. @dimwetoth - this is ready to publish now, correct?

**Comment by pajuric** [comment]
@natebower - Please review and provide editorial feedback on the content here.
