### ISSUE TITLE
New layout for `/blog` to be a bit more user friendly.

### ISSUE THREAD

**Issue by nateynateynate** [opensearch-project/project-website#2903]
Instead of a boring list of titles and excerpts, lets make this look more professional by using some kind of card layout. 

Consider the options at https://medium.com/geekculture/33-blog-card-css-for-web-design-726a037217b5

**Comment by kaimmej** [comment]
I support tackling this, I think we should move forward incrementally. 
Considering the options that Nate suggested in the description of this post, the majority of these are either Card structures with a top-image, or feed-structure and have side images to the left or right. 

Research: Looking at similar Jekyll themes for blogging [jekyllthemes.io](https://jekyllthemes.io/free)
- [clean blog](https://jekyllthemes.io/theme/startbootstrap-clean-blog-jekyll)
- [mundana](https://jekyllthemes.io/theme/mundana)
- [longhaul](https://jekyllthemes.io/theme/long-haul)

Lets make a clean, responsive look that follows something along the lines of the above. 


Responding to Nate's questions above: 
- (how many blogs should be displayed) this is very easy to change. We are currently displaying 5, and we have 50 pages worth of 5 blogs each. I suggest we up the page limit to 15, in order to drop the number of pages down. 
- (Do we want to archive old blog posts, so that our blog count doesnt approach infinity... ) I support this. I suggest we take down low view-count blogs, or past release announcements that are out of date to the current state of opensearch. 
- (Featured image) I think this is a good idea. We should be able to do this programattically and I think it makes sense to tie the featured image to the content, tags, category, or subject matter of the each blog post. Help needed - what metadata do we have available? and how might we begin to categorize our previous posts? 
- (generic image) a couple of options might be the latest OpenSearch version announcement, the authors image, or a generic brand picture. Maybe it makes sense to iterate through these options, so that the same generic image is never shown twice on a page. 


Will come back with potential design change options.

**Comment by kaimmej** [comment]
### Blog redesign preview:
Card style layout with a featured post on the front page
![Image](https://github.com/opensearch-project/project-website/assets/28766727/53d21d02-f47c-49ea-a685-40c29aab1eaf)

Paginator changed to a bootstrap nav style element 
It now shows the active page, and the "prev << chevrons" are grayed out if on the first page
> Before:
![Image](https://github.com/opensearch-project/project-website/assets/28766727/ccaf0597-4af9-4e3e-9f5e-5ed6475737d6)
> After:
![Image](https://github.com/opensearch-project/project-website/assets/28766727/81b97879-401a-4a62-b101-d8249441829c)

**Comment by pajuric** [comment]
I'd love to see a blog that is titled with a feature blog at the top and two sub-features under it - with the rest tiled.

**Comment by kaimmej** [comment]
> I'd love to see a blog that is titled with a feature blog at the top and two sub-features under it - with the rest tiled. Amd include images for every blog, along with a tagging structure.

Hi Patti, 
Great feedback! We wanted to push this change out there to show the new card layout and featured-post layouts. We want to now gather feedback from the community, in order to go back through and refine the blog-feed to become what it needs to be. 

#2935 
I have created another issue in order to gather ongoing feedback for the next week or two, where we will then update the blog feed, per the feedback we get. 
How does that sound?

**Comment by nateynateynate** [comment]
Immediate needs solved wtih #2983
