### ISSUE TITLE
[Blog] Some kind of intro to OpenSearch

### ISSUE THREAD

**Issue by nateynateynate** [opensearch-project/project-website#675]
**Describe the blog post your would like to write**

I hope to provide a blog that offers an introduction to OpenSearch that requires no prior knowledge whatsoever.  It will be meant for people who aren't quite sure what it does. It will include how it can supplement workflows, and some of the more popular use cases for which it is proficient. 

And a quick call to action for community contributions and why that is what makes us thrive. 

**What is the title of the blog post?**
`An OpenSearch Primer` (not sure 100% yet.)

**Who are the authors?**

Nate Boot

**What is the proposed posting date?**
Earliest, 2/11/2022 - Latest, 2/14/2022

**Comment by stockholmux** [comment]
I'm going to close this but I believe that @dblock  left some feedback on #690 that I couldn't easily address in your absence, @nateynateynate. 

Feel free to do another PR to address that feedback as needed - remember just because the b log post is published doesn't mean it's immutable. The website is software and software evolves.
