### ISSUE TITLE
[BLOG] ISM Shrink Shard  - Deep Dive

### ISSUE THREAD

**Issue by dtaivpp** [opensearch-project/project-website#853]
**Describe the blog post your would like to write**
We should create a blog that covers the technical details of how to use the ISM Shrink Shard action, why someone would want to use it, and what they can expect when using it.  

**What is the title of the blog post?**
TBD

**Who are the authors?**
Clay Downs (@downsrob) / David Tippett (@dtaivpp)

**What is the proposed posting date?**
6/24/2022

**Comment by dtaivpp** [comment]
https://github.com/opensearch-project/documentation-website/pull/657/commits/9020fdfb206c6028c37cfbb02a54ffe8ff3fe0cd#diff-1ab8395db79ee0a4853218fc8bb1413b961c7df49bf92c8e85879afdbd26cd28

Adding link to the new style guide.

**Comment by dtaivpp** [comment]
@natebower Would you mind looking over this outline for a blog that Clay and I are working on? This isn't the exact wording for the sections but the basics for what we will cover and how we might lay it out.  

# The Safest Way to Optimize OpenSearch's Shard Replication

##  What problems does this solve? 
- Optimizing helps you get the most out of your cluster
- Why someone would want to shrink primary shard number
- ISM allows for users to shrink with guardrails in place (describe why you want to do it through ISM)

##  Setting up a policy
1. ISM Policy for Shard Shrink
2. Specify Which Strategy (Percentage, Max Shard Size, Number of Final Shards)
    - Aliases and Force Unsafe options and why you would use them
 
 ## How it works
 - Give a little background on how the shrink operation works with regard to locking the index, duplicating the data, and re-indexing.

**Comment by dtaivpp** [comment]
@downsrob these are a few good blogs to look to for inspiration. 

https://opensearch.org/blog/technical-post/2022/05/opentelemetry-metrics-for-data-prepper/
- Does a good job integrating the technical with why someone would want to use it

https://opensearch.org/blog/intro/2022/03/fine-dining-for-indices/
- This one has a lot of personality and has some fun delivering technical content

**Comment by natebower** [comment]
@dtaivpp and @downsrob This looks good to me. Just a couple of comments, given that this is a preliminary outline: 1. Because we will have just described how to set up a policy, "How it works" is perhaps a little vague. How will what work? How will the content in this section differ from the content in the previous section? How are the sections related? I would be a little more clear regarding the structure. 2. What is the call to action? I love that we start by describing what problems we are solving, but we should also be clear about the call to action we are advocating.

Looking forward to seeing a draft!

**Comment by pajuric** [comment]
@dtaivpp  - Please provide an update or close if this is not moving forward.
