### ISSUE TITLE
[BUG] Minor editorial fixes on Download & Get Started page

### ISSUE THREAD

**Issue by macrakis** [opensearch-project/project-website#879]
**Describe the bug**
Various small editorial fixes for https://opensearch.org/downloads.html

**To Reproduce**
n/a

**Expected behavior**
"These steps will setup" => "These steps will set up" -- the verb "set up" is written as two words
"Setup your Docker host..." ditto
"OpenSearch provides SQL drivers like ODBC and JDBC, that let you..." remove comma before "that"
"driver for connecting business intelligence, and data visualization applications" remove comma

**Plugins**
n/a

**Screenshots**
n/a

**Host/Environment (please complete the following information):**
n/a

**Additional context**
I would have tried my hand at fixing it myself, but [project-website](https://github.com/opensearch-project/project-website)/downloads.html doesn't actually contain the text, and I don't know where to find it.

**Comment by hdhalter** [comment]
Can we also provide some introductory information to the page? Something like,  "To get started with OpenSearch, download the OpenSearch software appropriate for your environment, then go to the _Install and Configure OpenSearch_ documentation to configure OpenSearch. We also provide a variety of tools and drivers to support your OpenSearch installation. To get up and running quickly, try out OpenSearch with Docker Compose."

**Comment by dtaivpp** [comment]
@hdhalter I agree that we probably need some more introductory information but that may be best done when we revamp the remainder of the page. There is a fairly big initiative to get it overhauled so that it hits better with the appropriate audiences. Hopefully we can get a proposal together in the next few weeks for that. 

@macrakis let me take a look at that. I am not sure where all that lives either but I'll see what we can do.

**Comment by dtaivpp** [comment]
@macrakis can you look over these changes and make sure they all seem correct?
